### ISSUE TITLE
Suggestion: Use comparable benchmarker

### ISSUE THREAD

**Issue by Relequestual** [ahungrynoob/jsonschema#1]
There exists a benchmarking tool. It would be great if you could use that, which would allow your benchmark to be comparable.

https://github.com/ebdrup/json-schema-benchmark

**Comment by Relequestual** [comment]
Yikes! That's supprising!
Can you determine which tests were much slower?

**Comment by ahungrynoob** [comment]
@Relequestual All the tests, because the call of napi take huge overhead

**Comment by Relequestual** [comment]
OOOOh I understand. Damn.
Still, doesn't mean it's not useful for allowing different implementations to be testable!
